### ISSUE TITLE
big issue on build version 0.12.0

### ISSUE THREAD

**Issue by leon-andria** [aurelia/http-client#106]
The xhrType is undefined. So doing this will never work new _this.XHRType();
It's not a function nor a constructor.

var RequestMessageProcessor = (function () {
    function RequestMessageProcessor(xhrType, xhrTransformers) {
      _classCallCheck(this, RequestMessageProcessor);

      this.XHRType = xhrType;
      this.xhrTransformers = xhrTransformers;
      this.isAborted = false;
    }

....

 RequestMessageProcessor.prototype.process = function process(client, requestMessage) {
      var _this = this;

      var promise = new Promise(function (resolve, reject) {
        var xhr = _this.xhr = new _this.XHRType();

**Comment by heruan** [comment]
I confirm 0.12.0 throws a `TypeError: _this.XHRType is not a function`.

**Comment by devmondo** [comment]
i confirm two

**Comment by jdanyow** [comment]
Are you hitting this error in an aurelia application or in unit tests? 

If the issue occurs in unit tests, do the following to "initialize" the platform abstraction layer in your unit tests:

```
jspm install aurelia-pal
jspm install aurelia-pal-browser --dev
```

in any of the unit test files, add:

```javascript
import {initialize} from 'aurelia-pal-browser';
initialize();
```

If you're encountering this error in an Aurelia app, confirm you've jspm installed all of the aurelia dependencies listed in your package.json.  jspm update isn't enough.  Each needs to be re-installed.

Please report back if this helps-  I'm on the new build in both a plugin (aurelia-breeze) and in an Aurelia application.  Both use the HttpClient, neither are hitting this issue.  That said, I may not be using all the HttpClient functionality you guys are so I could be wrong on the above ^^^.

**Comment by heruan** [comment]
I'm hitting this error in an Aurelia application, with a clean `jspm install -y`. I'd be happy to help debug; this is the complete console error:
```
Unhandled promise rejection TypeError: _this.XHRType is not a function
    at http://localhost:9000/jspm/github/aurelia/http-client@0.12.0/aurelia-http-client.js:233:31
    at new Promise (http://localhost:9000/jspm/npm/core-js@0.9.18/modules/es6.promise.js:193:9)
    at RequestMessageProcessor.process (http://localhost:9000/jspm/github/aurelia/http-client@0.12.0/aurelia-http-client.js:232:21)
    at http://localhost:9000/jspm/github/aurelia/http-client@0.12.0/aurelia-http-client.js:723:26
    at run (http://localhost:9000/jspm/npm/core-js@0.9.18/modules/es6.promise.js:91:43)
    at http://localhost:9000/jspm/npm/core-js@0.9.18/modules/es6.promise.js:105:11
    at module.exports (http://localhost:9000/jspm/npm/core-js@0.9.18/modules/$.invoke.js:6:25)
    at queue.(anonymous function) (http://localhost:9000/jspm/npm/core-js@0.9.18/modules/$.task.js:40:9)
    at Number.run (http://localhost:9000/jspm/npm/core-js@0.9.18/modules/$.task.js:27:7)
    at listner (http://localhost:9000/jspm/npm/core-js@0.9.18/modules/$.task.js:31:9)
```

**Comment by jdanyow** [comment]
please `jspm install aurelia-_________` for each of the `aurelia-_____` items in your package.json

**Comment by heruan** [comment]
Thank you @jdanyow! Something changes, now the error is:
```
Unhandled promise rejection TypeError: this.metadata.initialize is not a function
    at ResourceDescription.initialize (http://localhost:9000/jspm/github/aurelia/templating@0.16.0/aurelia-templating.js:2314:21)
    at ResourceModule.initialize (http://localhost:9000/jspm/github/aurelia/templating@0.16.0/aurelia-templating.js:2233:17)
    at http://localhost:9000/jspm/github/aurelia/templating@0.16.0/aurelia-templating.js:2605:20
    at run (http://localhost:9000/jspm/npm/core-js@0.9.18/modules/es6.promise.js:91:43)
    at http://localhost:9000/jspm/npm/core-js@0.9.18/modules/es6.promise.js:105:11
    at module.exports (http://localhost:9000/jspm/npm/core-js@0.9.18/modules/$.invoke.js:6:25)
    at queue.(anonymous function) (http://localhost:9000/jspm/npm/core-js@0.9.18/modules/$.task.js:40:9)
    at Number.run (http://localhost:9000/jspm/npm/core-js@0.9.18/modules/$.task.js:27:7)
    at listner (http://localhost:9000/jspm/npm/core-js@0.9.18/modules/$.task.js:31:9)
```
Maybe some dependency is missing from the dependency hierarchy?

**Comment by ashirai** [comment]
I also confirm 0.12.0 throws a `TypeError: _this.XHRType is not a function`. This is not thrown in a Aurelia app not in unit tests.

**Comment by jdanyow** [comment]
see @EisenbergEffect's comment [here](https://github.com/aurelia/bootstrapper/issues/22#issuecomment-147869639).  It really sounds like your projects aren't fully updated- maybe you're using an aurelia plugin that hasn't been updated yet?  Execute `jspm clean` and then take a look at your `jspm_packages\github\aurelia` folder... any duplicate items would mean you have version forks that need cleaning up.

**Comment by heruan** [comment]
Then it's forks. I have these:
```
                     github:aurelia/binding 0.9.1 0.10.0
        github:aurelia/dependency-injection 0.10.1 0.11.0
            github:aurelia/event-aggregator 0.8.0 0.9.0
                   github:aurelia/framework 0.16.0 0.17.0
                      github:aurelia/loader 0.9.0 0.10.0
              github:aurelia/loader-default 0.10.0 0.11.0
                     github:aurelia/logging 0.7.0 0.8.0
                    github:aurelia/metadata 0.8.0 0.9.0
                        github:aurelia/path 0.9.0 0.10.0
                  github:aurelia/task-queue 0.7.0 0.8.0
                  github:aurelia/templating 0.15.3 0.16.0
                                npm:core-js 0.9.18 1.2.1
```
I'm trying to find out which plugin sticks to old versions, since I'm not able to clean the forks…

**Comment by heruan** [comment]
Found the plugins:  `aurelia-dialog` and `aurelia-i18n`.

**Comment by leon-andria** [comment]
I would like add that Aurelia-Validation too.

**Comment by zewa666** [comment]
@heruan I've updated aurelia-i18n, can you give it a try?

**Comment by ashirai** [comment]
@zewa666, I updated it to the aurelia-i18n 0.2.5 and now I am getting this error:
`Unhandled promise rejection TypeError: this.subscription is not a function
    at TCustomAttribute.unbind (http://localhost:9000/jspm_packages/github/aurelia/i18n@0.2.5/t.js:118:14)
    at Controller.unbind (http://localhost:9000/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:2724:20)
    at View.unbind (http://localhost:9000/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:841:26)
    at ViewFactory.returnViewToCache (http://localhost:9000/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:1731:14)
    at View.returnToCache (http://localhost:9000/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:753:24)
    at removeAction (http://localhost:9000/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:1246:25)
    at ViewSlot.removeAll (http://localhost:9000/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:1259:7)
    at CompositionEngine.createControllerAndSwap (http://localhost:9000/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:3541:49)
    at http://localhost:9000/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:3642:28
    at f (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1415:56)`

**Comment by EisenbergEffect** [comment]
@zewa666 The signature of the object that the event aggregator's subscribe returns has changed. It now returns an object with a `dispose` method.

**Comment by leon-andria** [comment]
@EisenbergEffect There is a chance that in futur libraries under "Aurelia" can be updated together when big "break changes" are applied.
I'm telling you that because we use so much aurelia and really can't afford that some part of libraries like i18n & validation can't be updated accordly to the latest build.
As I'm writing now, we are stuck to apply the latest build because some of libraries are not up to date.
Thank you for your support,

Léon

**Comment by zewa666** [comment]
@leon-andria its mostly my fault as I'm currently on vacation and not available most of the time, and my teams co-contributor currently is not available. Besides that such big breaking changes should only happen in before BETA and are likely to stop then.
So apologies and will get that done better next time :+1:

**Comment by leon-andria** [comment]
@zewa666 Thank you very much. I don't want to blame anyone, and i fully understand how you guys working hard, and get my respect. We are just a big FAN of Aurelia so that it's hard for us to explain to someone why it doesn't work, because this new release is just a "Killer". Can you think that you plan to roll-out over more than 400 web sites....

**Comment by zewa666** [comment]
thanks for the kind words. We will certainly talk internally more about a stable update process in the future so things like this one don't happen.

**Comment by EisenbergEffect** [comment]
We definitely here your concern on this. Please note that the libraries to which you are referring are plugins and can't actually be updated until after the core is released. There's a dependency order issue there that is unavoidable. However, we hope to have this process streamlined so that the lag is much shorter in the future (minutes or hours only, rather than days). This issue will also be less common after beta because we won't have breaking changes to core APIs, so a plugin won't need to update when the core changes, unless it depends on a new feature or API that wasn't there before. This will work itself out even better once we hit 1.0.0 because of the way that jspm works with semver; it can autoupdate anything that isn't a breaking change. Finally, we are working with the jspm team to have the concept of "peerDependencies" to jspm/system.js. Once that is in place, we will declare all Aurelia libraries and plugins to have peerDependencies rather than dependencies. This will also improve the update process.

**Comment by leon-andria** [comment]
Thank you Rob for your comment. The peerDependencies feature is just awesome.
We are really concerned for each updates as i said earlier, we have so many web sites (it's not just 10 or 20, it's more than 100..) with aurelia and some of them are already "Live".
As usual, great job.

**Comment by ofuentes15** [comment]
Sorry, maybe someone can help me, I didn't understand how to fixed, in this moment I have the version http-client@0.12.0, is the last one? How I fixed it? Thanks!

**Comment by suamikim** [comment]
I'm currently stuck on this one too and would really appreciate some help:

* I installed version `0.13.0` of the `http-client` using `jspm install github:aurelia/http-client`
* I executed `jspm install npm:aurelia___` for every `aurelia___` dependency in `package.json` as requested by jdanyow
* I don't see any duplicate entries in `jspm_packages/github/aurelia`
* Calling `http.put('the-path')` results in 3 errors in the console:  
  `Unhandled promise rejection TypeError: _this.XHRType is not a function` followed by 2 subsequent `Unhandled promise rejection TypeError: _aureliaPal.DOM.createCustomEvent is not a function`

Please let me know what I can do to fix this issue!
Thanks & best regards

**Comment by suamikim** [comment]
I just found the solution myself:
Instead of installing the `http-client` with `jspm install github:aurelia/http-client`, simply using `jspm install aurelia-http-client` did the trick and everything works fine now!

**Comment by WisdomCorp** [comment]
Guys any update on this issue, still getting same error as mentioned by suamikim above. 

I did Jspm clean, install etc. Any update will be helpful. 

Thanks

**Comment by EisenbergEffect** [comment]
Make sure you are actually using a beta version, not a pre-beta.

**Comment by WisdomCorp** [comment]
"aurelia-fetch-client": "github:aurelia/fetch-client@0.4.0",   
    "aurelia-http-client": "npm:aurelia-http-client@1.0.0-beta.1.1.1",
    "aurelia-i18n": "github:aurelia/i18n@0.2.6",

This is in my config.js

**Comment by EisenbergEffect** [comment]
Are you trying to use fetch-client or http-client? Those are two different libraries.

**Comment by WisdomCorp** [comment]
I am using http-client

**Comment by EisenbergEffect** [comment]
You should remove the fetch client for sure then. Try running jspm update as well.

**Comment by EisenbergEffect** [comment]
Make sure you don't have any forks.

**Comment by WisdomCorp** [comment]
Ok. Let me do it, as well I have seen some duplicate entries in my config.js after jspm install, so let me verify it and I will remove fetch client.

**Comment by WisdomCorp** [comment]
hello,

      "aurelia-animator-css": "npm:aurelia-animator-css@^1.0.0-beta.1.1.1",
      "aurelia-binding": "npm:aurelia-binding@^1.0.0-beta.1.1.3",
      "aurelia-bootstrapper": "npm:aurelia-bootstrapper@^1.0.0-beta.1.1.2",
      "aurelia-breeze": "npm:aurelia-breeze@^1.0.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@^1.0.0-beta.1.1.3",
      "aurelia-dialog": "npm:aurelia-dialog@^0.5.6",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@^1.0.0-beta.1.1.1",

I was individually doing jspm install for all aurelia.* modules above as mentioned by @jdanyow .......when I reached upto the that library its started working :). I don't know though which one had issue.

**Comment by BrightShadow** [comment]
Hi all what worked form me:
- remove completely jspm_packages and node_modules
   rimraf jspm_packages
   rimraf nopde_modules

- uninstall jspm globally and locally (npm unsinstall -g jspm, npm uninstall jspm)
- remove a cache folder for jspm: /c/Users/<user>/AppData/Local/jspm
- then I'v installed Python 2.x (some NPM install parts needed it)
- then I've started again installing jspm locally and globally

It didn't work, but I didn't have any problems with NPM install , jspm install

- then I've run:  jspm upgrade

And it solves problems with:
Unhandled promise rejection TypeError: _aureliaPal.DOM.injectStyles is not a function(…)

After all steps I've got working app again.

**Comment by markadrake** [comment]
Ran into this issue after installing an Aurelia plugin via JSPM. Nothing worked until I ran `jspm upgrade` - did the trick for me. I was running older versions of just about everything in Aurelia.

**Comment by richcobrien** [comment]
New to Aurelia and going through the video and documentation examples. Wanted to use both 'fetch' and 'http' on the same example page. Had to run `jspm update` and the aurelia-http-client fired right up.

Note: I'm on windows and noticed that I ran 'update' as 'upgrade' was not available.
